### ISSUE TITLE
google search link showing up on wikipedia listing for an advertiser

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#16] opened 2018-04-26 16:50 UTC
@AddisonFreeman I did a search for "norton software" and this came up.  I thought you fixed this already in the past...

<img width="697" alt="screen shot 2018-04-26 at 12 48 35 pm" src="https://user-images.githubusercontent.com/28393235/39319847-58a869d0-4950-11e8-80e8-5d3141fa276f.png">

**Comment by robgpeak** [comment] 2018-04-26 17:25
This might be a separate issue, but I also just noticed on that same search, the search results just below the wikipedia page was for norton software on walmart.com, but we did NOT appear above that listing like we should have.  However, if I do a search to "buy a toaster" we DO show up above the walmart listing...?

<img width="731" alt="screen shot 2018-04-26 at 1 20 45 pm" src="https://user-images.githubusercontent.com/28393235/39321395-e743e0f8-4954-11e8-8b2a-25765798712e.png">

**Comment by AddisonFreeman** [comment] 2018-04-26 17:57
This issue has not been fixed. I'm still working with chad on how to
correctly parse the domains.

**Comment by AddisonFreeman** [comment] 2018-04-26 18:14
The original issue was
https://github.com/robgpeak/CL-WebExtension/issues/12#issue-317643696 with
stores.petco.com and www.petco.com

**Comment by AddisonFreeman** [comment] 2018-04-26 19:41
Duplicate of https://github.com/robgpeak/CL-WebExtension/issues/12

**Closed by AddisonFreeman** 2018-04-26 19:41 UTC
