### ISSUE TITLE
Web Browser Extension

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#1] opened 2018-03-08 22:22 UTC
Here is the thread where we can all communicate regarding the development of the web extension

**Comment by robgpeak** [comment] 2018-03-08 22:23
Here is how Azigo is doing it…  https://secure.extensiondownload.com/mall.smashcash.net  and https://secure.extensiondownload.com/azigo.partnersmall.com with seemingly one extension for all of their subdomains...

**Comment by AddisonFreeman** [comment] 2018-03-12 23:49
https://developer.chrome.com/extensions/browserAction#method-setIcon

method for redrawing the browser icon when a subdomain icon is received from the back end.

**Comment by robgpeak** [comment] 2018-03-12 23:53
As far as the logo within the extension itself that should be found at the top of xclub Complinks.Co

**Comment by robgpeak** [comment] 2018-03-13 01:36
One very important thing to consider is that we are going to need to have the ability to quickly include or exclude an advertiser from showing up in the extension from our back end. That would probably mean adding a field to the database that says "DSA";true," instead of just "isAdvertiser":true,

**Comment by cgladue** [comment] 2018-03-13 01:42
there is a field in the database already named "extensionEnabled" that is true by default.

**Comment by robgpeak** [comment] 2018-03-13 13:12
Cool.  So @AddisonFreeman that is the field we want to use as to whether or not that particular advertiser even triggers the action of showing the extension pop up to a user.  So even though a particular advertiser might be listed on our site, their specific T&Cs may not allow us to display their logo or links in a DSA (Downloadable Software Application).  This would also mean if someone did a search on Google and one of our advertisers was in the search results and they were set to "extensionEnabled" false, then we would not show an icon and/or link for CompLinks. Does that make sense?

**Comment by AddisonFreeman** [comment] 2018-03-14 21:28
@robgpeak @cgladue is that field coming through an endpoint? I don't see it in the checkDomain call. 
<img width="290" alt="screen shot 2018-03-14 at 3 52 40 pm" src="https://user-images.githubusercontent.com/5950267/37431956-b784c020-27a4-11e8-9ffb-7b771bd1db6e.png">

**Comment by cgladue** [comment] 2018-03-14 21:41
No it’s not expose anywhere at the moment I was curious if you wanted to have a discussion about what data that you need in the API so that I can modify those APIs are old and I’m sure we could make it more to what you need if you just tell me the data you want

**Comment by AddisonFreeman** [comment] 2018-03-14 21:54
Just made an initial commit to this repo of the full extension with a proof of the dynamic extension icon. I've added a 5 second delay to change the icon when you click the popup button. Go ahead and test it out.

**Comment by AddisonFreeman** [comment] 2018-03-14 22:25
Made another commit that sets valid google search results to red text (will keep improving for adding icon next to result title)
<img width="634" alt="screen shot 2018-03-14 at 5 23 07 pm" src="https://user-images.githubusercontent.com/5950267/37434159-a5f008da-27ac-11e8-98ba-e3bb5783f932.png">
Go ahead and try this feature out as well.

**Comment by AddisonFreeman** [comment] 2018-03-14 22:43
This should be a larger conversation of how the data should be organized.
I'd hate for you to keep making one-off changes.

**Comment by cgladue** [comment] 2018-03-14 22:45
Trust me I’m used to it.  No worries at all.

**Comment by AddisonFreeman** [comment] 2018-03-14 23:47
Haha, alright then. Please add it to the checkDomain API response and tell
me a domain that it is false on I can check.

**Comment by cgladue** [comment] 2018-03-16 01:47
ok it should be thee now, the property name is **extensionEnabled**

**Comment by AddisonFreeman** [comment] 2018-03-16 22:41
I've added a boolean check for google search result and popups not to appear if it's false for that domain.

**Comment by AddisonFreeman** [comment] 2018-03-19 17:14
@cgladue @robgpeak Do we have a way of knowing the correct subdomain extension icon from a user's email address? I could use that image (base64 encoded) as an api field to change the icon once the user enters their email address.

**Comment by cgladue** [comment] 2018-03-19 17:18
users email is not unique in our system, the unique key is email address
and domain that they registered on ...

I wanted to talk to you about this and maybe a new issue would be best ...
hoe do you want to handle authenticating the user ?  can you read
authentication cookies on the users PC ?  or would you need an API to let
them login the first time and then persist that going forward ?





Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment] 2018-03-19 17:28
They can select their domain from a dropdown and maybe the authentication
process can be an emailed auth link?

**Comment by cgladue** [comment] 2018-03-19 17:30
i think rob would want it to be automatic, like know which domain you are
registered with and if if cant do it by loking at the auth cookies on the
pc then a dropdown and email/password that gets entered perhaps ?
@robgpeak what do you think



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment] 2018-03-19 17:54
automatic would be a MUCH better user experience.

**Comment by AddisonFreeman** [comment] 2018-03-19 18:21
Oh I see, that cookie is already saved on the browser, it just runs a check
for which it is. Got it. Any resources for the name of that cookie
currently and how I can recreate?

**Comment by cgladue** [comment] 2018-03-19 18:35
it might be possible to send you a cookie as part of an AJAX call, and you
would then store it on the users browser, since the ASP Authentication
cookie is encrypted witht he servers machine key i dont think we want to
put that key anywhere a user could see it.

we would have to test this approach, but in theory it seems like it would
work...



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment] 2018-03-19 22:42
Really that would only need to be done once every time the browser
extension is loaded, the icon will stay changed.

**Comment by cgladue** [comment] 2018-03-20 00:34
Hey @AddisonFreeman i just added a few issues to the list so you can modify the request and response from the API ... also the APIs will now require an authenticated user to be able to use them, if they are logged into the website already then they will be able to hit them OK, otherwise they can login via the authenticate call.  Also you will need to direct the API call to the proper subdomain, not sure how you want to determine which subdomain they should be using, i dont know if it can be automatic fromt he extension since its generic, it may need a dropdown, what do you think of for possible ideas ?

**Comment by robgpeak** [comment] 2018-03-20 00:40
I don't want to speak out of turn, and I might not be reading it or understanding it correctly, but we can't let the user pick the sub domain from a dropdown menu, if that's what you were talking about Chad...

**Comment by cgladue** [comment] 2018-03-20 00:42
ok, i have no idea how you would authenticate the user if they are on
bestbuy.com and the extension pops open a window and asks you to login
otherwise, no other extension that i know if has this problem since they
are all under the same domain.  so its a unique issue we will have to think
of a way to deal with.  any thoughts ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment] 2018-03-20 00:48
Not sure either, but I think Azigo is doing it that way.  And I would think since they have many different partners and subdomainsbe, I would think they would also NOT email addresses be unique throughout their entire network of partners. 

Let's see what Addison says.

**Comment by AddisonFreeman** [comment] 2018-03-20 14:43
If each subdomian has a cookie placed on their user's computer we can read that to get the proper extension. Don't know how difficult that would be to manage. I think that's the solution you suggested earlier @robgpeak.

**Comment by cgladue** [comment] 2018-03-20 14:45
right now when you call the authenticate method of the API it will
authenticate the users and place a cookie for the domain... but the problem
would be for the users who arent logged in (no cookie), how do you know
which domain to authenticate them against ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment] 2018-03-21 18:41
Yes, the latter is the way to go. The only way the extension can know where a user installed the extension from is if the referring page saves a cookie that the browser later reads. This would have the correct icon from that subdomain but the user would still need to manually log into the extension with a username (does this currently) and password (what @cgladue says it will be in the future) in order to start seeing offers.

**Comment by robgpeak** [comment] 2018-03-21 18:46
I think the best thing to do would be to get a working prototype, (of which I know Chad has done a lot of the heavy lifting, but we need Addison to polish it), so we can see a semblance of UI/UX and make assessments and adjustments from there.

**Comment by AddisonFreeman** [comment] 2018-03-21 19:09
What if there was a default email so users could see offers and then be prompted to login for real when they checkout?

**Comment by cgladue** [comment] 2018-03-21 19:13
Offers change based on the domain they are registered for.  The points/$ can be different.

**Comment by AddisonFreeman** [comment] 2018-03-21 22:41
Push an update @robgpeak. I didn't realize the old api changed too so you couldn't test it earlier, you can now. I added a password field and logout button to the settings page.

**Comment by AddisonFreeman** [comment] 2018-03-21 23:42
Let's do a quick check in call tomorrow @robgpeak if you're available

**Comment by robgpeak** [comment] 2018-03-22 02:28
Yeah, for sure.  I just installed 1.3.3 and I am not sure what I am looking for, but I don't see what changed.  Talk to you tomorrow.

**Comment by robgpeak** [comment] 2018-03-28 13:54
Addison, let me know when I can check out the new version.

**Comment by robgpeak** [comment] 2018-03-29 16:36
@AddisonFreeman I would like to see an update as to where we are with the extension?

**Comment by AddisonFreeman** [comment] 2018-03-29 16:38
I'm getting back to the design today after some work on the authentication cookie. Can we have a check in call in a few hours? @robgpeak

**Comment by robgpeak** [comment] 2018-03-29 16:40
sure

**Comment by robgpeak** [comment] 2018-03-30 18:47
just watched CL-subdomains-demo.mov and I get the subdomain difference. Cool.  

As for the look and color, I did not see a difference.  Meaning, I would have thought the shop.complinks.co version would have had the blue theme look that the site has, and the click to activate button color would match the exact button color of the shop now buttons on the that subdomain.  and the same would be true for the color scheme for xclub...
It looks like you are pulling this info from the API yes?

Also, I think we should use slightly radiuses on the corners of the notification slide out, as well what will be the main extension window.  And if you can add a drop shadow to the overall slide out and main extension window, that would be great.  Actually, while you're in there, the "Activate X points/$1 spent" button should also have a drop shadow so it matches the look and feel of the Shop Now buttons on the websites.  

Lastly, maybe and accent color border around the notification slide out, as well the main extension windows to dress it up a bit and make it look pretty.

**Comment by AddisonFreeman** [comment] 2018-03-30 20:37
I'll address these style changes. The color not changing was a issue that
chad and I are fixing now.

**Comment by robgpeak** [comment] 2018-04-03 12:47
@AddisonFreeman Here is a crude mock up of what I think the look should be...

If the "X" at the top right is a problem, then just go with the text link under the activate button that reads, "No thanks, maybe next time" to close the window.

<img width="568" alt="screen shot 2018-04-03 at 8 43 44 am" src="https://user-images.githubusercontent.com/28393235/38249938-5c72860a-371b-11e8-9e47-a3bf68b8c091.png">

**Comment by AddisonFreeman** [comment] 2018-04-03 14:08
I can make the X, I'll send a working update today.

**Comment by robgpeak** [comment] 2018-04-06 16:31
@AddisonFreeman Here is the mock up of how it would look for the image and buttons over each enabled advertiser in a google search result...  And the actual images to the left of the buttons are included below this screenshot mock up.  Please use the naming convention "shop_re_google.png" and "xclub_re_google.png" respectively for the names of the images.  In essence it is, "{subdomain}_re_google.png"  re is for rewards everywhere...  

We want to keep them as PNG so they retain the transparent background

If you have the ability to make the colors of the images "Exactly" match that of the primary notification colors of the respective subdomains, as well as the button colors, please do that.

<img width="642" alt="screen shot 2018-04-06 at 12 16 02 pm" src="https://user-images.githubusercontent.com/28393235/38432173-a1200f7c-3994-11e8-9e50-254a846b29b8.png">

<img alt="complinks_re_google" src="https://user-images.githubusercontent.com/28393235/38432201-b0b8d6b2-3994-11e8-8100-f69655d6fc2b.png">

<img alt="xclub_re_google" src="https://user-images.githubusercontent.com/28393235/38432217-bcf3a7ae-3994-11e8-9c89-c6d870784d0a.png">

**Comment by robgpeak** [comment] 2018-04-10 15:49
@AddisonFreeman @cgladue I would like to get phase 2 of the extension done today.  Phase 2 is the part that will allow the Rewards Everywhere logo and button show up in the google search result for advertisers that are extension enabled "true".

**Comment by AddisonFreeman** [comment] 2018-04-10 15:55
Chad, were you able to get the smaller logo into the getUserDetail call?

**Comment by cgladue** [comment] 2018-04-11 20:25
It should be in the call now.  Rob will need to upload the images via the backend under the property edit page. Then it will show up for you to use.

**Comment by robgpeak** [comment] 2018-04-11 20:43
I just uploaded the search results logos for both shop and xclub.  Very nice functionality in the back end @cgladue 

@AddisonFreeman please let me know how to test it?   Will it work with all the extension enabled "true" advertisers?

**Comment by AddisonFreeman** [comment] 2018-04-11 21:43
Yes, if the notification would appear on the page itself, the coupon will
appear on the search results like the mockup you sent.

Chad, what is the new field name? I'm not seeing it yet.

**Comment by cgladue** [comment] 2018-04-11 21:46
searchResultsLogoUrl

Let me check on it.

**Comment by AddisonFreeman** [comment] 2018-04-11 21:46
Oh I see it now, searchResultLogo url. It's still null.

**Comment by AddisonFreeman** [comment] 2018-04-11 22:06
Working now, thanks.

**Comment by cgladue** [comment] 2018-04-11 22:07
Check again

**Comment by AddisonFreeman** [comment] 2018-04-11 23:50
This is almost done, I'm just getting the page to show that you've been
activated after you've been redirected. I push what's done if you want to
check, Rob.

**Comment by robgpeak** [comment] 2018-04-11 23:52
Sure.  Push it and let me have a look

**Comment by AddisonFreeman** [comment] 2018-04-12 17:02
It should have gone through, let me check again.

**Comment by AddisonFreeman** [comment] 2018-04-12 17:07
Just pushed, sorry about that delay.

**Comment by AddisonFreeman** [comment] 2018-04-19 20:55
@robgpeak @cgladue The activate link redirects to a shop.complinks/xclub.complinks subdomain page (on bestbuy at least). Just making sure y'all are aware.

**Comment by cgladue** [comment] 2018-04-19 21:05
what page does it redirect to ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment] 2018-04-19 21:13
https://shop.complinks.co/stores/index/6712

**Comment by cgladue** [comment] 2018-04-19 21:14
hmm, this is related to something we needed to change as it relates to the
starting of trips...

are you able to set a custom http header on the GET request that happens
when they click the link ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment] 2018-04-20 05:42
I can, yes.

**Comment by robgpeak** [comment] 2018-04-20 14:35
@AddisonFreeman Please get me an update on the status.

**Comment by AddisonFreeman** [comment] 2018-04-20 17:37
A bit of a roadblock coming from the backend.

1) The checkDomain call is not working as described with passing an array
of strings, waiting to hear back from Chad on this (
https://github.com/robgpeak/CL-WebExtension/issues/7#issuecomment-382888562)

2) Activated trips are not starting as they used to, the link that used to
redirect back to the referring page now stops at a subdomain link.
(mentioned on this thread a few comments above).

I'm blocked until these are resolved.

**Comment by cgladue** [comment] 2018-04-20 17:44
Addsion, i see the content-type header is set to x-www-form-urlencoded in
your screenshots, this should be JSON and not form data

Request:

{
  "domainName" : [ "macys.com", "godaddy.com" ]
}

Response;

[
    {
        "isAdvertiser": true,
        "extensionEnabled": true,
        "advertiserName": "Macys.com",
        "clickUrl":
"https://shop.complinks.co/trip/start?aid=6789&lid=0&url=https%3a%2f%2fclick.linksynergy.com%2ffs-bin%2fclick%3fid%3djLQ8qrFPMSA%26offerid%3d486109.100258994%26type%3d3",
        "logoUrl":
"https://s3.us-east-2.amazonaws.com/complinks/logos/lg_3184.jpg",
        "reward": "1.5 points/$1 spent",
        "domainName": "macys.com"
    },
    {
        "isAdvertiser": true,
        "extensionEnabled": true,
        "advertiserName": "GoDaddy.com",
        "clickUrl":
"https://shop.complinks.co/trip/start?aid=11&lid=0&url=http%3a%2f%2fwww.kqzyfj.com%2fclick-8235261-10378406-1491592212000",
        "logoUrl":
"https://s3.us-east-2.amazonaws.com/complinks/logos/1513033.jpg",
        "reward": "up to 7.5 points/$1 spent",
        "domainName": "godaddy.com"
    }
]





Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment] 2018-04-20 18:31
and for the start trip links, can you set a http header named "X-Extension"
and set it to "true" for the value right before you sent the click over to
the site, then it shouldnt redirect you tot he store page.



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment] 2018-04-20 19:13
<img width="258" alt="screen shot 2018-04-20 at 12 08 40 pm" src="https://user-images.githubusercontent.com/5950267/39069183-d50f83b2-4493-11e8-997b-629d2c89a5fe.png">
Can you test this on the Notification activate button @robgpeak to verify that it starts a trip on the back end. I need to jump off my computer but will be back to get this working on the popup activate button as well in a few hours.

The google search result page is using the new combined api call but it is still slow loading on my connection. Please test that on your end as well. 

Everything recent is pushed now.

**Comment by robgpeak** [comment] 2018-04-20 20:34
Still not working properly, and now there are other issues.  Please have a look https://screencast.com/t/LEDTOZSRA

**Comment by AddisonFreeman** [comment] 2018-04-20 22:03
I'll look at the style issues now. When it says activated, it sent a request to the subdomain page in the background, I wanted to know if you can verify that a trip started. 

@cgladue I can send an ajax call with that custom header, I don't think it's possible to redirect with a header, it would be a normal page redirect after the first one is sent via ajax.

**Comment by robgpeak** [comment] 2018-04-20 22:12
Yes it does track a shopping trip, but it does not refresh the page the way it does if you click on a notification from say ebates for example, and my spider senses tell me it needs to for compliance purposes...  Please have a read.

[downloadable_service_agreement_2-2-15-v2PDF.pdf](https://github.com/robgpeak/CL-WebExtension/files/1933817/downloadable_service_agreement_2-2-15-v2PDF.pdf)

and take a look at https://pubhelp.rakutenmarketing.com/hc/en-us/articles/200965808-Downloadable-Software-Applications-DSAs-An-Overview too

**Comment by robgpeak** [comment] 2018-04-20 22:26
Not sure what's going on with the extension, but I just did an arbitrary search on google, and I saw these results with out logo and button above a link which is NOT one of our advertisers...  slideshare.net...?  What are you doing @AddisonFreeman ???  :)  The smiley face is to keep it light because you don't know me as long as Chad does, where if it was him, I would tell him to keep his tiny mice under control and get his shit together... LOL

<img width="692" alt="screen shot 2018-04-20 at 6 20 24 pm" src="https://user-images.githubusercontent.com/28393235/39076190-e73f138e-44c7-11e8-9da2-d1718e6801b4.png">

**Comment by AddisonFreeman** [comment] 2018-04-21 00:02
The strange results was from cleaning up the urls incorrectly and the
response sent back a result for (on the wikipedia example) the domain "en."

I'm about to push a fix for that and the macy's styling fix, that one was
because macy's had a stylesheet that overrode the extension style (really
the macy's developers broke a best practice so I had to make a workaround).

Addison

**Comment by AddisonFreeman** [comment] 2018-04-21 00:03
Chad, do you know why the activation link doesn't redirect like it used to?

**Comment by AddisonFreeman** [comment] 2018-04-21 00:16
Here's an example of the false positive. pbs.org got parsed wrong and here's what what sent back for the domain "pbs"

<img width="352" alt="screen shot 2018-04-20 at 5 14 10 pm" src="https://user-images.githubusercontent.com/5950267/39078376-6009568a-44be-11e8-8c05-1aa6a0088c0d.png">

I just pushed the latest. The search result is still coming in slow, I can revisit tomorrow to try and use javascript selectors instead of jQuery and some more speed tools to find the slowdown.

**Comment by cgladue** [comment] 2018-04-21 01:45
like i said we locked it down to only allow redirects from local webpages
(those that have a referrer set to *.complinks.co) and to redirect to the
store page for everyone else to comply with the referral program
networks...  the web extension will not be coming from a referrer on .
complinks.co tho so i will have to create a new URL that you will follow to
redirect, you wont have to do anything, that url will be sent in the
startTripLink property that you are using today..

ok the link should now be correct and work for you ...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment] 2018-04-21 16:16
@AddisonFreeman I just went to cj.com to look into something and I saw this...  What the heck is going on???  First it should not even be there, and next the image is broken!!!

<img width="1220" alt="screen shot 2018-04-21 at 12 14 22 pm" src="https://user-images.githubusercontent.com/28393235/39086327-bd30789e-455d-11e8-915d-fff632f21e10.png">

**Comment by cgladue** [comment] 2018-04-21 16:25
looks to me like the width was too big for the Container its displayed in
so it wrapped to the next line ...  but i dont know for sure.

but i assume it should be an easy css fix



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment] 2018-04-21 16:45
Its the site overridding the style rules I believe. I'll check that and
make ours more specific.

**Comment by cgladue** [comment] 2018-04-21 17:33
the false positives should be fixed now i think



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment] 2018-04-21 19:42
@robgpeak I addressed the styling, it should work now. I optimized the google code using the new call and it's still slow loading. Tell me your thoughts, do you notice a difference? I just pushed.

I'm trying to figure out where the delay is coming from, @cgladue do you notice a one second server delay elsewhere? 
<img width="399" alt="screen shot 2018-04-21 at 12 24 01 pm" src="https://user-images.githubusercontent.com/5950267/39087985-00fb316c-455f-11e8-8ad0-34eb275f2de5.png">

I took out the jquery operations that loops over the search results and it's still slow to return 
<img width="391" alt="screen shot 2018-04-21 at 12 41 08 pm" src="https://user-images.githubusercontent.com/5950267/39088116-6961ffae-4561-11e8-8a6f-60eaf40913e7.png">

**Comment by robgpeak** [comment] 2018-04-21 20:07
@AddisonFreeman I gotta say, now I am getting frustrated.  I just installed the latest extension, it still says 1.3.7 which is the same number as last time.  The links are NOT showing up above the google listings at all.  They ARE appearing on some sites, but not all that are marked as extension enabled in the back end.

Then just looking at an example of what the notification looks like, and it is not good looking.  It needs to be better looking and make sure all the text for the activate button show up on the same line...

<img width="1099" alt="screen shot 2018-04-21 at 4 02 32 pm" src="https://user-images.githubusercontent.com/28393235/39088343-1798d5e0-457e-11e8-94de-3e3a7fe4fb31.png">

**Comment by AddisonFreeman** [comment] 2018-04-21 20:51
The version number has to be manually updated, which I forgot to do, my apologies. 

Extension enabled error is not totally in my control. Please tell me the sites you are seeing the issue on and Chad and I will investigate further.

This style is because of extra words in the deal text. I had allowed for 3 extra spaces in the points field, but not the 6 additional characters from the added "up to " 
<img width="607" alt="screen shot 2018-04-21 at 1 47 41 pm" src="https://user-images.githubusercontent.com/5950267/39088651-d2e8f9ec-456a-11e8-82d4-f248ef34b42f.png">
just pushed again, reducing the font to allow for these extra characters. it is version 1.3.8.

**Comment by AddisonFreeman** [comment] 2018-04-21 20:52
now it looks like this
<img width="598" alt="screen shot 2018-04-21 at 1 52 01 pm" src="https://user-images.githubusercontent.com/5950267/39088681-2fe7de38-456b-11e8-9638-30dcd1814d8b.png">

**Comment by AddisonFreeman** [comment] 2018-04-22 19:46
Just pushed again, It's working on google and all the domains you sent
above for me. It is tricky with all the overriding styles so I tried to
make them all look as similar as possible but the width of the button may
look different with different character lengths on the specific deal. The
version I pushed is 1.3.9.

**Comment by robgpeak** [comment] 2018-04-22 22:51
Seems to be working...  One thing I noticed is the left and right hand side.  After this is fixed I will start a new issue for Phase 3 so it is easier to follow.
<img width="1085" alt="screen shot 2018-04-22 at 6 46 29 pm" src="https://user-images.githubusercontent.com/28393235/39100823-f6d64294-465d-11e8-94d1-c15f58ffffb1.png">
 of the notification box don't line up...

**Comment by AddisonFreeman** [comment] 2018-04-23 00:00
Just pushed 1.3.10, the issue has to do with style overrides on the img
element. Let me know if you see this on any other site because I'm not
convinced I've figured out the root of the cause with this fix.

**Closed** 2018-04-26 15:37 UTC
